/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * EdusyncERPAPI
 * Edusync ERP API documentation (Development)
 * OpenAPI spec version: v1
 */

export interface AcademicProgramDto {
  programName?: string;
  shortName?: string;
  yearFirstImplemented?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  collegeId?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  programTypeId?: number | string;
}
