/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * EdusyncERPAPI
 * Edusync ERP API documentation (Development)
 * OpenAPI spec version: v1
 */

export interface CampusDto {
  campusName: string;
  campusShortName: string;
  address: string;
  latitude: number;
  longitude: number;
  agencyId: number;
}
