/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * EdusyncERPAPI
 * Edusync ERP API documentation (Development)
 * OpenAPI spec version: v1
 */

export interface CollegeDto {
  collegeName: string;
  collegeShortName: string;
  campusId: number;
}
