/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * EdusyncERPAPI
 * Edusync ERP API documentation (Development)
 * OpenAPI spec version: v1
 */

export interface CourseDto {
  courseTitle: string;
  courseCode: string;
  courseDescription: string;
  withLaboratory: boolean;
  isSpecialize: boolean;
  lectureUnits: number;
  laboratoryUnits: number;
  creditUnits: number;
  isImportedFromOldSystem: boolean;
  courseId?: number;
  skillsFrameworkTrackSpecializationId: number;
}
