/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * EdusyncERPAPI
 * Edusync ERP API documentation (Development)
 * OpenAPI spec version: v1
 */

export type CreateAgencyBody = {
  AgencyName?: string;
  ShortName?: string;
  Address?: string;
  Code?: string;
  IsDefault?: boolean;
};
