/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * EdusyncERPAPI
 * Edusync ERP API documentation (Development)
 * OpenAPI spec version: v1
 */

export interface CurriculumDto {
  curriculumName: string;
  curriculumCode: string;
  major: string;
  minor: string;
  authorityLegal: string;
  totalAcademicTerm: number;
  minUnitsToBeHonored: number;
  startDate: string;
  endDate: string;
  maxUnits: number;
  isActive: boolean;
  isDefault: boolean;
  academicTermId: number;
  academicProgramId: number;
}
