/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * EdusyncERPAPI
 * Edusync ERP API documentation (Development)
 * OpenAPI spec version: v1
 */

export interface CurriculumDto {
  curriculumName?: string;
  curriculumCode?: string;
  major?: string;
  minor?: string;
  authorityLegal?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalAcademicTerm?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  minUnitsToBeHonored?: number | string;
  startDate?: string;
  endDate?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  maxUnits?: number | string;
  isActive?: boolean;
  isDefault?: boolean;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  academicTermId?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  academicProgramId?: number | string;
}
