/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * EdusyncERPAPI
 * Edusync ERP API documentation (Development)
 * OpenAPI spec version: v1
 */

export interface CycleDto {
  cycleDescription?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  cycleNumber?: number | string;
  startDate?: string;
  endDate?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  campusId?: number | string;
}
