/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * EdusyncERPAPI
 * Edusync ERP API documentation (Development)
 * OpenAPI spec version: v1
 */
import type { GetCollegeDto } from './getCollegeDto';
import type { GetProgramTypeDto } from './getProgramTypeDto';

export interface GetAcademicProgramDto {
  programName: string;
  shortName: string;
  yearFirstImplemented: string;
  collegeId: number;
  college: GetCollegeDto;
  programTypeId: number;
  programType: GetProgramTypeDto;
  id: number;
}
