/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * EdusyncERPAPI
 * Edusync ERP API documentation (Development)
 * OpenAPI spec version: v1
 */
import type { GetCampusDto } from './getCampusDto';

export interface GetAgencyDto {
  agencyName?: string;
  shortName?: string;
  address?: string;
  code?: string;
  isDefault?: boolean;
  campuses?: GetCampusDto[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: number | string;
}
