/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * EdusyncERPAPI
 * Edusync ERP API documentation (Development)
 * OpenAPI spec version: v1
 */

export interface GetAcademicTermDto {
  label?: string;
  description?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  gradingPeriods?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: number | string;
}
