/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * EdusyncERPAPI
 * Edusync ERP API documentation (Development)
 * OpenAPI spec version: v1
 */
import type { GetCollegeDto } from "./getCollegeDto";
import type { GetProgramTypeDto } from "./getProgramTypeDto";

export interface GetAcademicProgramDto {
  programName?: string;
  shortName?: string;
  yearFirstImplemented?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  collegeId?: number | string;
  college?: GetCollegeDto;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  programTypeId?: number | string;
  programType?: GetProgramTypeDto;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: number | string;
}
