/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * EdusyncERPAPI
 * Edusync ERP API documentation (Development)
 * OpenAPI spec version: v1
 */
import type { GetCampusDto } from './getCampusDto';
import type { GetRoomDto } from './getRoomDto';

export interface GetBuildingDto {
  buildingName: string;
  latitude: number;
  longitude: number;
  campusId: number;
  campus: GetCampusDto;
  rooms?: GetRoomDto[];
  id: number;
}
