/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * EdusyncERPAPI
 * Edusync ERP API documentation (Development)
 * OpenAPI spec version: v1
 */
import type { GetCampusDto } from './getCampusDto';
import type { GetRoomDto } from './getRoomDto';

export interface GetBuildingDto {
  buildingName?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  latitude?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  longitude?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  campusId?: number | string;
  campus?: GetCampusDto;
  rooms?: GetRoomDto[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: number | string;
}
