/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * EdusyncERPAPI
 * Edusync ERP API documentation (Development)
 * OpenAPI spec version: v1
 */
import type { GetAgencyDto } from './getAgencyDto';

export interface GetCampusDto {
  campusName: string;
  campusShortName: string;
  address: string;
  latitude: number;
  longitude: number;
  agencyId: number;
  agency: GetAgencyDto;
  id: number;
}
