/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * EdusyncERPAPI
 * Edusync ERP API documentation (Development)
 * OpenAPI spec version: v1
 */
import type { GetCampusDto } from './getCampusDto';

export interface GetCycleDto {
  cycleDescription: string;
  cycleNumber: number;
  startDate: string;
  endDate: string;
  campusId: number;
  campus: GetCampusDto;
  id: number;
}
