/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * EdusyncERPAPI
 * Edusync ERP API documentation (Development)
 * OpenAPI spec version: v1
 */
import type { GetAgencyDto } from "./getAgencyDto";

export interface GetCampusDto {
  campusName?: string;
  campusShortName?: string;
  address?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  latitude?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  longitude?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  agencyId?: number | string;
  agency?: GetAgencyDto;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: number | string;
}
