/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * EdusyncERPAPI
 * Edusync ERP API documentation (Development)
 * OpenAPI spec version: v1
 */
import type { GetAcademicProgramDto } from './getAcademicProgramDto';
import type { GetAcademicTermDto } from './getAcademicTermDto';

export interface GetCurriculumDto {
  curriculumName: string;
  curriculumCode: string;
  major: string;
  minor: string;
  authorityLegal: string;
  totalAcademicTerm: number;
  minUnitsToBeHonored: number;
  startDate: string;
  endDate: string;
  maxUnits: number;
  isActive: boolean;
  isDefault: boolean;
  academicTermId: number;
  academicTerm: GetAcademicTermDto;
  academicProgramId: number;
  academicProgram: GetAcademicProgramDto;
  id: number;
}
