/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * EdusyncERPAPI
 * Edusync ERP API documentation (Development)
 * OpenAPI spec version: v1
 */
import type { GetCampusDto } from './getCampusDto';

export interface GetCycleDto {
  cycleDescription?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  cycleNumber?: number | string;
  startDate?: string;
  endDate?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  campusId?: number | string;
  campus?: GetCampusDto;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: number | string;
}
