/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * EdusyncERPAPI
 * Edusync ERP API documentation (Development)
 * OpenAPI spec version: v1
 */
import type { GetSkillsFrameworkTrackSpecializationDto } from './getSkillsFrameworkTrackSpecializationDto';

export interface GetCourseDto {
  courseTitle: string;
  courseCode: string;
  courseDescription: string;
  withLaboratory: boolean;
  isSpecialize: boolean;
  lectureUnits: number;
  laboratoryUnits: number;
  creditUnits: number;
  isImportedFromOldSystem: boolean;
  courseId?: number;
  parentCourse?: null | GetCourseDto;
  skillsFrameworkTrackSpecializationId: number;
  skillsFrameworkTrackSpecialization: GetSkillsFrameworkTrackSpecializationDto;
  id: number;
}
