/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * EdusyncERPAPI
 * Edusync ERP API documentation (Development)
 * OpenAPI spec version: v1
 */
import type { GetCampusDto } from './getCampusDto';

export interface GetCollegeDto {
  collegeName: string;
  collegeShortName: string;
  campusId: number;
  campus: GetCampusDto;
  id: number;
}
