/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * EdusyncERPAPI
 * Edusync ERP API documentation (Development)
 * OpenAPI spec version: v1
 */

export interface GetEducationalQualityAssuranceTypeDto {
  name: string;
  shortName: string;
  eqaLabel1: string;
  eqaLabel2: string;
  eqaLabel3: string;
  eqaLabel4: string;
  eqaLabel5: string;
  eqaLabel6: string;
  eqaLabel7: string;
  eqaLabel8: string;
  id: number;
}
