/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * EdusyncERPAPI
 * Edusync ERP API documentation (Development)
 * OpenAPI spec version: v1
 */

export interface GetErrorDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  code?: number | string;
  file: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  line?: number | string;
  member: string;
  message: string;
}
