/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * EdusyncERPAPI
 * Edusync ERP API documentation (Development)
 * OpenAPI spec version: v1
 */
import type { GetAgencyDto } from './getAgencyDto';
import type { KpiTypeEnum } from './kpiTypeEnum';

export interface GetKpiDto {
  kpiName: string;
  kpiDescription: string;
  kpiCode: string;
  isPercentage: boolean;
  sortOrder: number;
  kpiStandard: number;
  kpiType: KpiTypeEnum;
  agencyId: number;
  agency: GetAgencyDto;
  id: number;
}
