/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * EdusyncERPAPI
 * Edusync ERP API documentation (Development)
 * OpenAPI spec version: v1
 */

export interface GetMachineInfoDto {
  hostOS?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  ramUsed?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  ramAvailable?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  cpuUsage?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  cpuCores?: number | string;
}
