/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * EdusyncERPAPI
 * Edusync ERP API documentation (Development)
 * OpenAPI spec version: v1
 */
import type { GetSkillsFrameworkTrackSpecializationDto } from './getSkillsFrameworkTrackSpecializationDto';
import type { PaginationMeta } from './paginationMeta';

export interface GetPaginatedResponseDtoOfGetSkillsFrameworkTrackSpecializationDto {
  data: GetSkillsFrameworkTrackSpecializationDto[];
  paginationMeta: PaginationMeta;
}
