/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * EdusyncERPAPI
 * Edusync ERP API documentation (Development)
 * OpenAPI spec version: v1
 */

export type GetPaginatedEducationalQualityAssuranceTypeParams = {
  Fresh?: boolean;
  Search?: string;
  Filter?: string;
  /**
   * @pattern ^-?(?:0|[1-9]\d*)$
   */
  Page?: number | string;
  /**
   * @pattern ^-?(?:0|[1-9]\d*)$
   */
  Rows?: number | string;
};
