/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * EdusyncERPAPI
 * Edusync ERP API documentation (Development)
 * OpenAPI spec version: v1
 */
import type { GetKpiDto } from "./getKpiDto";
import type { PaginationMeta } from "./paginationMeta";

export interface GetPaginatedResponseDtoOfGetKpiDto {
  data: GetKpiDto[];
  paginationMeta: PaginationMeta;
}
