/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * EdusyncERPAPI
 * Edusync ERP API documentation (Development)
 * OpenAPI spec version: v1
 */

export type GetPaginatedAcademicProgramParams = {
  Fresh?: boolean;
  Search?: string;
  Filter?: string;
  Page?: number;
  Rows?: number;
};
