/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * EdusyncERPAPI
 * Edusync ERP API documentation (Development)
 * OpenAPI spec version: v1
 */
import type { GetSectorDisciplineDto } from './getSectorDisciplineDto';
import type { PaginationMeta } from './paginationMeta';

export interface GetPaginatedResponseDtoOfGetSectorDisciplineDto {
  data: GetSectorDisciplineDto[];
  paginationMeta: PaginationMeta;
}
