/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * EdusyncERPAPI
 * Edusync ERP API documentation (Development)
 * OpenAPI spec version: v1
 */
import type { GetBuildingDto } from './getBuildingDto';

export interface GetRoomDto {
  roomName: string;
  capacity: number;
  isLab: boolean;
  isSpecializedLab: boolean;
  buildingId: number;
  building: GetBuildingDto;
  id: number;
}
