/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * EdusyncERPAPI
 * Edusync ERP API documentation (Development)
 * OpenAPI spec version: v1
 */
import type { GetSectorDisciplineDto } from './getSectorDisciplineDto';

export interface GetSkillsFrameworkTrackSpecializationDto {
  trackSpecialization?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  sectorDisciplineId?: number | string;
  sectorDiscipline?: GetSectorDisciplineDto;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: number | string;
}
