/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * EdusyncERPAPI
 * Edusync ERP API documentation (Development)
 * OpenAPI spec version: v1
 */
import type { GetEducationalQualityAssuranceTypeDto } from './getEducationalQualityAssuranceTypeDto';

export interface GetSectorDisciplineDto {
  sectorDisciplineName: string;
  disciplineDescription: string;
  sectorDisciplineId?: number;
  parentSectorDiscipline?: null | GetSectorDisciplineDto;
  educationalQualityAssuranceTypeId?: number;
  educationalQualityAssuranceType?: null | GetEducationalQualityAssuranceTypeDto;
  id: number;
}
