/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * EdusyncERPAPI
 * Edusync ERP API documentation (Development)
 * OpenAPI spec version: v1
 */
import type { GetEducationalQualityAssuranceTypeDto } from './getEducationalQualityAssuranceTypeDto';

export interface GetSectorDisciplineDto {
  sectorDisciplineName?: string;
  disciplineDescription?: string;
  /**
   * @nullable
   * @pattern ^-?(?:0|[1-9]\d*)$
   */
  sectorDisciplineId?: number | string | null;
  parentSectorDiscipline?: null | GetSectorDisciplineDto;
  /**
   * @nullable
   * @pattern ^-?(?:0|[1-9]\d*)$
   */
  educationalQualityAssuranceTypeId?: number | string | null;
  educationalQualityAssuranceType?: null | GetEducationalQualityAssuranceTypeDto;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: number | string;
}
