/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * EdusyncERPAPI
 * Edusync ERP API documentation (Development)
 * OpenAPI spec version: v1
 */

export * from './academicProgramDto';
export * from './academicTermDto';
export * from './agencyDto';
export * from './authDataDto';
export * from './buildingDto';
export * from './campusDto';
export * from './collegeDto';
export * from './courseDto';
export * from './createAgencyBody';
export * from './curriculumDto';
export * from './cycleDto';
export * from './educationalQualityAssuranceTypeDto';
export * from './externalTokenLoginDto';
export * from './getAcademicProgramDto';
export * from './getAcademicTermDto';
export * from './getAgencyDto';
export * from './getBuildingDto';
export * from './getCampusDto';
export * from './getCollegeDto';
export * from './getCourseDto';
export * from './getCurriculumDto';
export * from './getCycleDto';
export * from './getCycleGroupedByYearDto';
export * from './getEducationalQualityAssuranceTypeDto';
export * from './getErrorDto';
export * from './getKpiDto';
export * from './getMachineInfoDto';
export * from './getPaginatedAcademicProgramParams';
export * from './getPaginatedAcademicTermParams';
export * from './getPaginatedAgencyParams';
export * from './getPaginatedBuildingParams';
export * from './getPaginatedCampusCyclesGroupedByYearParams';
export * from './getPaginatedCampusParams';
export * from './getPaginatedCollegeParams';
export * from './getPaginatedCourseParams';
export * from './getPaginatedCurriculumParams';
export * from './getPaginatedCycleParams';
export * from './getPaginatedEducationalQualityAssuranceTypeParams';
export * from './getPaginatedKpiParams';
export * from './getPaginatedProgramTypeParams';
export * from './getPaginatedResponseDtoOfGetAcademicProgramDto';
export * from './getPaginatedResponseDtoOfGetAcademicTermDto';
export * from './getPaginatedResponseDtoOfGetAgencyDto';
export * from './getPaginatedResponseDtoOfGetBuildingDto';
export * from './getPaginatedResponseDtoOfGetCampusDto';
export * from './getPaginatedResponseDtoOfGetCollegeDto';
export * from './getPaginatedResponseDtoOfGetCourseDto';
export * from './getPaginatedResponseDtoOfGetCurriculumDto';
export * from './getPaginatedResponseDtoOfGetCycleDto';
export * from './getPaginatedResponseDtoOfGetCycleGroupedByYearDto';
export * from './getPaginatedResponseDtoOfGetEducationalQualityAssuranceTypeDto';
export * from './getPaginatedResponseDtoOfGetKpiDto';
export * from './getPaginatedResponseDtoOfGetProgramTypeDto';
export * from './getPaginatedResponseDtoOfGetRoomDto';
export * from './getPaginatedResponseDtoOfGetSectorDisciplineDto';
export * from './getPaginatedResponseDtoOfGetSkillsFrameworkTrackSpecializationDto';
export * from './getPaginatedResponseDtoOfGetUserDto';
export * from './getPaginatedRoomParams';
export * from './getPaginatedSectorDisciplineParams';
export * from './getPaginatedSkillsFrameworkTrackSpecializationParams';
export * from './getPaginatedUserParams';
export * from './getProgramTypeDto';
export * from './getRoomDto';
export * from './getSectorDisciplineDto';
export * from './getSkillsFrameworkTrackSpecializationDto';
export * from './getUserDto';
export * from './guestUserRegistrationDto';
export * from './kpiDto';
export * from './kpiTypeEnum';
export * from './loginDto';
export * from './paginationMeta';
export * from './programTypeDto';
export * from './roomDto';
export * from './sectorDisciplineDto';
export * from './skillsFrameworkTrackSpecializationDto';
export * from './userDto';
