/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * EdusyncERPAPI
 * Edusync ERP API documentation (Development)
 * OpenAPI spec version: v1
 */
import type { KpiTypeEnum } from './kpiTypeEnum';

export interface KpiDto {
  kpiName?: string;
  kpiDescription?: string;
  kpiCode?: string;
  isPercentage?: boolean;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  sortOrder?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  kpiStandard?: number | string;
  kpiType?: KpiTypeEnum;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  agencyId?: number | string;
}
