/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * EdusyncERPAPI
 * Edusync ERP API documentation (Development)
 * OpenAPI spec version: v1
 */

export interface RoomDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  capacity?: number | string;
  isLab?: boolean;
  isSpecializedLab?: boolean;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  buildingId?: number | string;
}
