/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * EdusyncERPAPI
 * Edusync ERP API documentation (Development)
 * OpenAPI spec version: v1
 */
import type {
  AcademicProgramDto,
  AcademicTermDto,
  AgencyDto,
  AuthDataDto,
  BuildingDto,
  CampusDto,
  CollegeDto,
  CourseDto,
  CreateAgencyBody,
  CurriculumDto,
  EducationalQualityAssuranceTypeDto,
  ExternalTokenLoginDto,
  GetAcademicProgramDto,
  GetAcademicTermDto,
  GetAgencyDto,
  GetBuildingDto,
  GetCampusDto,
  GetCollegeDto,
  GetCourseDto,
  GetCurriculumDto,
  GetEducationalQualityAssuranceTypeDto,
  GetKpiDto,
  GetMachineInfoDto,
  GetPaginatedAcademicProgramParams,
  GetPaginatedAcademicTermParams,
  GetPaginatedAgencyParams,
  GetPaginatedBuildingParams,
  GetPaginatedCampusParams,
  GetPaginatedCollegeParams,
  GetPaginatedCourseParams,
  GetPaginatedCurriculumParams,
  GetPaginatedEducationalQualityAssuranceTypeParams,
  GetPaginatedKpiParams,
  GetPaginatedProgramTypeParams,
  GetPaginatedResponseDtoOfGetAcademicProgramDto,
  GetPaginatedResponseDtoOfGetAcademicTermDto,
  GetPaginatedResponseDtoOfGetAgencyDto,
  GetPaginatedResponseDtoOfGetBuildingDto,
  GetPaginatedResponseDtoOfGetCampusDto,
  GetPaginatedResponseDtoOfGetCollegeDto,
  GetPaginatedResponseDtoOfGetCourseDto,
  GetPaginatedResponseDtoOfGetCurriculumDto,
  GetPaginatedResponseDtoOfGetEducationalQualityAssuranceTypeDto,
  GetPaginatedResponseDtoOfGetKpiDto,
  GetPaginatedResponseDtoOfGetProgramTypeDto,
  GetPaginatedResponseDtoOfGetRoomDto,
  GetPaginatedResponseDtoOfGetSectorDisciplineDto,
  GetPaginatedResponseDtoOfGetSkillsFrameworkTrackSpecializationDto,
  GetPaginatedResponseDtoOfGetUserDto,
  GetPaginatedRoomParams,
  GetPaginatedSectorDisciplineParams,
  GetPaginatedSkillsFrameworkTrackSpecializationParams,
  GetPaginatedUserParams,
  GetProgramTypeDto,
  GetRoomDto,
  GetSectorDisciplineDto,
  GetSkillsFrameworkTrackSpecializationDto,
  GetUserDto,
  GuestUserRegistrationDto,
  KpiDto,
  LoginDto,
  ProgramTypeDto,
  RoomDto,
  SectorDisciplineDto,
  SkillsFrameworkTrackSpecializationDto,
  UserDto,
} from "./model";

import { customInstance } from "../orval-client/axios-instance";

export const getEdusyncERPAPI = () => {
  const getOpenapiJson = () => {
    return customInstance<void>({ url: `/openapi.json`, method: "GET" });
  };

  /**
   * Fetches detailed information about a specific academicprogram using their identifier.
   * @summary Retrieve a academicprogram by ID
   */
  const getAcademicProgramById = (id: number) => {
    return customInstance<GetAcademicProgramDto>({
      url: `/Api/AcademicProgram/${id}`,
      method: "GET",
    });
  };

  /**
   * Retrieves a paginated list of all academicprograms available in the system.
   * @summary Retrieve paginated academicprograms
   */
  const getPaginatedAcademicProgram = (
    params?: GetPaginatedAcademicProgramParams,
  ) => {
    return customInstance<GetPaginatedResponseDtoOfGetAcademicProgramDto>({
      url: `/Api/AcademicProgram/paginate`,
      method: "GET",
      params,
    });
  };

  /**
   * Registers a new academicprogram record in the system based on the provided data.
   * @summary Create a new academicprogram
   */
  const createAcademicProgram = (academicProgramDto: AcademicProgramDto) => {
    return customInstance<GetAcademicProgramDto>({
      url: `/Api/AcademicProgram/create`,
      method: "POST",
      headers: { "Content-Type": "application/json-patch+json" },
      data: academicProgramDto,
    });
  };

  /**
   * Modifies existing academicprogram details using the specified unique identifier and provided payload.
   * @summary Update existing academicprogram
   */
  const updateAcademicProgram = (
    id: number,
    academicProgramDto: AcademicProgramDto,
  ) => {
    return customInstance<GetAcademicProgramDto>({
      url: `/Api/AcademicProgram/update/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json-patch+json" },
      data: academicProgramDto,
    });
  };

  /**
   * Permanently removes a academicprogram record from the system based on the provided identifier.
   * @summary Delete an existing academicprogram
   */
  const deleteAcademicProgram = (id: number) => {
    return customInstance<void>({
      url: `/Api/AcademicProgram/delete/${id}`,
      method: "DELETE",
    });
  };

  /**
   * Fetches detailed information about a specific academicterm using their identifier.
   * @summary Retrieve a academicterm by ID
   */
  const getAcademicTermById = (id: number) => {
    return customInstance<GetAcademicTermDto>({
      url: `/Api/AcademicTerm/${id}`,
      method: "GET",
    });
  };

  /**
   * Retrieves a paginated list of all academicterms available in the system.
   * @summary Retrieve paginated academicterms
   */
  const getPaginatedAcademicTerm = (
    params?: GetPaginatedAcademicTermParams,
  ) => {
    return customInstance<GetPaginatedResponseDtoOfGetAcademicTermDto>({
      url: `/Api/AcademicTerm/paginate`,
      method: "GET",
      params,
    });
  };

  /**
   * Registers a new academicterm record in the system based on the provided data.
   * @summary Create a new academicterm
   */
  const createAcademicTerm = (academicTermDto: AcademicTermDto) => {
    return customInstance<GetAcademicTermDto>({
      url: `/Api/AcademicTerm/create`,
      method: "POST",
      headers: { "Content-Type": "application/json-patch+json" },
      data: academicTermDto,
    });
  };

  /**
   * Modifies existing academicterm details using the specified unique identifier and provided payload.
   * @summary Update existing academicterm
   */
  const updateAcademicTerm = (id: number, academicTermDto: AcademicTermDto) => {
    return customInstance<GetAcademicTermDto>({
      url: `/Api/AcademicTerm/update/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json-patch+json" },
      data: academicTermDto,
    });
  };

  /**
   * Permanently removes a academicterm record from the system based on the provided identifier.
   * @summary Delete an existing academicterm
   */
  const deleteAcademicTerm = (id: number) => {
    return customInstance<void>({
      url: `/Api/AcademicTerm/delete/${id}`,
      method: "DELETE",
    });
  };

  /**
   * Fetches detailed information about a specific agency using their identifier.
   * @summary Retrieve a agency by ID
   */
  const getAgencyById = (id: number) => {
    return customInstance<GetAgencyDto>({
      url: `/Api/Agency/${id}`,
      method: "GET",
    });
  };

  /**
   * Retrieves a paginated list of all agencys available in the system.
   * @summary Retrieve paginated agencys
   */
  const getPaginatedAgency = (params?: GetPaginatedAgencyParams) => {
    return customInstance<GetPaginatedResponseDtoOfGetAgencyDto>({
      url: `/Api/Agency/paginate`,
      method: "GET",
      params,
    });
  };

  /**
   * Registers a new agency record in the system based on the provided data.
   * @summary Create a new agency
   */
  const createAgency = (createAgencyBody: CreateAgencyBody) => {
    const formUrlEncoded = new URLSearchParams();
    if (createAgencyBody.AgencyName !== undefined) {
      formUrlEncoded.append(`AgencyName`, createAgencyBody.AgencyName);
    }
    if (createAgencyBody.ShortName !== undefined) {
      formUrlEncoded.append(`ShortName`, createAgencyBody.ShortName);
    }
    if (createAgencyBody.Address !== undefined) {
      formUrlEncoded.append(`Address`, createAgencyBody.Address);
    }
    if (createAgencyBody.Code !== undefined) {
      formUrlEncoded.append(`Code`, createAgencyBody.Code);
    }
    if (createAgencyBody.IsDefault !== undefined) {
      formUrlEncoded.append(`IsDefault`, createAgencyBody.IsDefault.toString());
    }

    return customInstance<GetAgencyDto>({
      url: `/Api/Agency/create`,
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      data: formUrlEncoded,
    });
  };

  /**
   * Modifies existing agency details using the specified unique identifier and provided payload.
   * @summary Update existing agency
   */
  const updateAgency = (id: number, agencyDto: AgencyDto) => {
    return customInstance<GetAgencyDto>({
      url: `/Api/Agency/update/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json-patch+json" },
      data: agencyDto,
    });
  };

  /**
   * Permanently removes a agency record from the system based on the provided identifier.
   * @summary Delete an existing agency
   */
  const deleteAgency = (id: number) => {
    return customInstance<void>({
      url: `/Api/Agency/delete/${id}`,
      method: "DELETE",
    });
  };

  /**
   * Login attempt using credential.
   * @summary Login using email and password
   */
  const login = (loginDto: LoginDto) => {
    return customInstance<AuthDataDto>({
      url: `/Api/Auth/login`,
      method: "POST",
      headers: { "Content-Type": "application/json-patch+json" },
      data: loginDto,
    });
  };

  /**
   * Verifies a Google ID token and returns API JWT + refresh token.
   * @summary Login with Google ID token
   */
  const googleLogin = (externalTokenLoginDto: ExternalTokenLoginDto) => {
    return customInstance<AuthDataDto>({
      url: `/Api/Auth/google`,
      method: "POST",
      headers: { "Content-Type": "application/json-patch+json" },
      data: externalTokenLoginDto,
    });
  };

  /**
   * Verifies a Microsoft Entra ID token and returns API JWT + refresh token.
   * @summary Login with Microsoft ID token
   */
  const microsoftLogin = (externalTokenLoginDto: ExternalTokenLoginDto) => {
    return customInstance<AuthDataDto>({
      url: `/Api/Auth/microsoft`,
      method: "POST",
      headers: { "Content-Type": "application/json-patch+json" },
      data: externalTokenLoginDto,
    });
  };

  /**
   * Returns the currently authenticated user from the active JWT session.
   * @summary Get current session user
   */
  const getSession = () => {
    return customInstance<GetUserDto>({
      url: `/Api/Auth/session`,
      method: "GET",
    });
  };

  /**
   * Creates a new guest user account and returns the created user profile.
   * @summary Register a guest user
   */
  const registerGuest = (
    guestUserRegistrationDto: GuestUserRegistrationDto,
  ) => {
    return customInstance<GetUserDto>({
      url: `/Api/Auth/register`,
      method: "POST",
      headers: { "Content-Type": "application/json-patch+json" },
      data: guestUserRegistrationDto,
    });
  };

  /**
   * Signs out the current user session.
   * @summary Logout current session
   */
  const logout = () => {
    return customInstance<void>({ url: `/Api/Auth/logout`, method: "POST" });
  };

  /**
   * Fetches detailed information about a specific building using their identifier.
   * @summary Retrieve a building by ID
   */
  const getBuildingById = (id: number) => {
    return customInstance<GetBuildingDto>({
      url: `/Api/Building/${id}`,
      method: "GET",
    });
  };

  /**
   * Retrieves a paginated list of all buildings available in the system.
   * @summary Retrieve paginated buildings
   */
  const getPaginatedBuilding = (params?: GetPaginatedBuildingParams) => {
    return customInstance<GetPaginatedResponseDtoOfGetBuildingDto>({
      url: `/Api/Building/paginate`,
      method: "GET",
      params,
    });
  };

  /**
   * Registers a new building record in the system based on the provided data.
   * @summary Create a new building
   */
  const createBuilding = (buildingDto: BuildingDto) => {
    return customInstance<GetBuildingDto>({
      url: `/Api/Building/create`,
      method: "POST",
      headers: { "Content-Type": "application/json-patch+json" },
      data: buildingDto,
    });
  };

  /**
   * Modifies existing building details using the specified unique identifier and provided payload.
   * @summary Update existing building
   */
  const updateBuilding = (id: number, buildingDto: BuildingDto) => {
    return customInstance<GetBuildingDto>({
      url: `/Api/Building/update/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json-patch+json" },
      data: buildingDto,
    });
  };

  /**
   * Permanently removes a building record from the system based on the provided identifier.
   * @summary Delete an existing building
   */
  const deleteBuilding = (id: number) => {
    return customInstance<void>({
      url: `/Api/Building/delete/${id}`,
      method: "DELETE",
    });
  };

  /**
   * Fetches detailed information about a specific campus using their identifier.
   * @summary Retrieve a campus by ID
   */
  const getCampusById = (id: number) => {
    return customInstance<GetCampusDto>({
      url: `/Api/Campus/${id}`,
      method: "GET",
    });
  };

  /**
   * Retrieves a paginated list of all campuss available in the system.
   * @summary Retrieve paginated campuss
   */
  const getPaginatedCampus = (params?: GetPaginatedCampusParams) => {
    return customInstance<GetPaginatedResponseDtoOfGetCampusDto>({
      url: `/Api/Campus/paginate`,
      method: "GET",
      params,
    });
  };

  /**
   * Registers a new campus record in the system based on the provided data.
   * @summary Create a new campus
   */
  const createCampus = (campusDto: CampusDto) => {
    return customInstance<GetCampusDto>({
      url: `/Api/Campus/create`,
      method: "POST",
      headers: { "Content-Type": "application/json-patch+json" },
      data: campusDto,
    });
  };

  /**
   * Modifies existing campus details using the specified unique identifier and provided payload.
   * @summary Update existing campus
   */
  const updateCampus = (id: number, campusDto: CampusDto) => {
    return customInstance<GetCampusDto>({
      url: `/Api/Campus/update/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json-patch+json" },
      data: campusDto,
    });
  };

  /**
   * Permanently removes a campus record from the system based on the provided identifier.
   * @summary Delete an existing campus
   */
  const deleteCampus = (id: number) => {
    return customInstance<void>({
      url: `/Api/Campus/delete/${id}`,
      method: "DELETE",
    });
  };

  /**
   * Fetches detailed information about a specific college using their identifier.
   * @summary Retrieve a college by ID
   */
  const getCollegeById = (id: number) => {
    return customInstance<GetCollegeDto>({
      url: `/Api/College/${id}`,
      method: "GET",
    });
  };

  /**
   * Retrieves a paginated list of all colleges available in the system.
   * @summary Retrieve paginated colleges
   */
  const getPaginatedCollege = (params?: GetPaginatedCollegeParams) => {
    return customInstance<GetPaginatedResponseDtoOfGetCollegeDto>({
      url: `/Api/College/paginate`,
      method: "GET",
      params,
    });
  };

  /**
   * Registers a new college record in the system based on the provided data.
   * @summary Create a new college
   */
  const createCollege = (collegeDto: CollegeDto) => {
    return customInstance<GetCollegeDto>({
      url: `/Api/College/create`,
      method: "POST",
      headers: { "Content-Type": "application/json-patch+json" },
      data: collegeDto,
    });
  };

  /**
   * Modifies existing college details using the specified unique identifier and provided payload.
   * @summary Update existing college
   */
  const updateCollege = (id: number, collegeDto: CollegeDto) => {
    return customInstance<GetCollegeDto>({
      url: `/Api/College/update/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json-patch+json" },
      data: collegeDto,
    });
  };

  /**
   * Permanently removes a college record from the system based on the provided identifier.
   * @summary Delete an existing college
   */
  const deleteCollege = (id: number) => {
    return customInstance<void>({
      url: `/Api/College/delete/${id}`,
      method: "DELETE",
    });
  };

  /**
   * Fetches detailed information about a specific course using their identifier.
   * @summary Retrieve a course by ID
   */
  const getCourseById = (id: number) => {
    return customInstance<GetCourseDto>({
      url: `/Api/Course/${id}`,
      method: "GET",
    });
  };

  /**
   * Retrieves a paginated list of all courses available in the system.
   * @summary Retrieve paginated courses
   */
  const getPaginatedCourse = (params?: GetPaginatedCourseParams) => {
    return customInstance<GetPaginatedResponseDtoOfGetCourseDto>({
      url: `/Api/Course/paginate`,
      method: "GET",
      params,
    });
  };

  /**
   * Registers a new course record in the system based on the provided data.
   * @summary Create a new course
   */
  const createCourse = (courseDto: CourseDto) => {
    return customInstance<GetCourseDto>({
      url: `/Api/Course/create`,
      method: "POST",
      headers: { "Content-Type": "application/json-patch+json" },
      data: courseDto,
    });
  };

  /**
   * Modifies existing course details using the specified unique identifier and provided payload.
   * @summary Update existing course
   */
  const updateCourse = (id: number, courseDto: CourseDto) => {
    return customInstance<GetCourseDto>({
      url: `/Api/Course/update/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json-patch+json" },
      data: courseDto,
    });
  };

  /**
   * Permanently removes a course record from the system based on the provided identifier.
   * @summary Delete an existing course
   */
  const deleteCourse = (id: number) => {
    return customInstance<void>({
      url: `/Api/Course/delete/${id}`,
      method: "DELETE",
    });
  };

  /**
   * Fetches detailed information about a specific curriculum using their identifier.
   * @summary Retrieve a curriculum by ID
   */
  const getCurriculumById = (id: number) => {
    return customInstance<GetCurriculumDto>({
      url: `/Api/Curriculum/${id}`,
      method: "GET",
    });
  };

  /**
   * Retrieves a paginated list of all curriculums available in the system.
   * @summary Retrieve paginated curriculums
   */
  const getPaginatedCurriculum = (params?: GetPaginatedCurriculumParams) => {
    return customInstance<GetPaginatedResponseDtoOfGetCurriculumDto>({
      url: `/Api/Curriculum/paginate`,
      method: "GET",
      params,
    });
  };

  /**
   * Registers a new curriculum record in the system based on the provided data.
   * @summary Create a new curriculum
   */
  const createCurriculum = (curriculumDto: CurriculumDto) => {
    return customInstance<GetCurriculumDto>({
      url: `/Api/Curriculum/create`,
      method: "POST",
      headers: { "Content-Type": "application/json-patch+json" },
      data: curriculumDto,
    });
  };

  /**
   * Modifies existing curriculum details using the specified unique identifier and provided payload.
   * @summary Update existing curriculum
   */
  const updateCurriculum = (id: number, curriculumDto: CurriculumDto) => {
    return customInstance<GetCurriculumDto>({
      url: `/Api/Curriculum/update/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json-patch+json" },
      data: curriculumDto,
    });
  };

  /**
   * Permanently removes a curriculum record from the system based on the provided identifier.
   * @summary Delete an existing curriculum
   */
  const deleteCurriculum = (id: number) => {
    return customInstance<void>({
      url: `/Api/Curriculum/delete/${id}`,
      method: "DELETE",
    });
  };

  /**
   * Fetches detailed information about a specific educationalqualityassurancetype using their identifier.
   * @summary Retrieve a educationalqualityassurancetype by ID
   */
  const getEducationalQualityAssuranceTypeById = (id: number) => {
    return customInstance<GetEducationalQualityAssuranceTypeDto>({
      url: `/Api/EducationalQualityAssuranceType/${id}`,
      method: "GET",
    });
  };

  /**
   * Retrieves a paginated list of all educationalqualityassurancetypes available in the system.
   * @summary Retrieve paginated educationalqualityassurancetypes
   */
  const getPaginatedEducationalQualityAssuranceType = (
    params?: GetPaginatedEducationalQualityAssuranceTypeParams,
  ) => {
    return customInstance<GetPaginatedResponseDtoOfGetEducationalQualityAssuranceTypeDto>(
      {
        url: `/Api/EducationalQualityAssuranceType/paginate`,
        method: "GET",
        params,
      },
    );
  };

  /**
   * Registers a new educationalqualityassurancetype record in the system based on the provided data.
   * @summary Create a new educationalqualityassurancetype
   */
  const createEducationalQualityAssuranceType = (
    educationalQualityAssuranceTypeDto: EducationalQualityAssuranceTypeDto,
  ) => {
    return customInstance<GetEducationalQualityAssuranceTypeDto>({
      url: `/Api/EducationalQualityAssuranceType/create`,
      method: "POST",
      headers: { "Content-Type": "application/json-patch+json" },
      data: educationalQualityAssuranceTypeDto,
    });
  };

  /**
   * Modifies existing educationalqualityassurancetype details using the specified unique identifier and provided payload.
   * @summary Update existing educationalqualityassurancetype
   */
  const updateEducationalQualityAssuranceType = (
    id: number,
    educationalQualityAssuranceTypeDto: EducationalQualityAssuranceTypeDto,
  ) => {
    return customInstance<GetEducationalQualityAssuranceTypeDto>({
      url: `/Api/EducationalQualityAssuranceType/update/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json-patch+json" },
      data: educationalQualityAssuranceTypeDto,
    });
  };

  /**
   * Permanently removes a educationalqualityassurancetype record from the system based on the provided identifier.
   * @summary Delete an existing educationalqualityassurancetype
   */
  const deleteEducationalQualityAssuranceType = (id: number) => {
    return customInstance<void>({
      url: `/Api/EducationalQualityAssuranceType/delete/${id}`,
      method: "DELETE",
    });
  };

  /**
   * Fetches detailed information about a specific kpi using their identifier.
   * @summary Retrieve a kpi by ID
   */
  const getKpiById = (id: number) => {
    return customInstance<GetKpiDto>({ url: `/Api/Kpi/${id}`, method: "GET" });
  };

  /**
   * Retrieves a paginated list of all kpis available in the system.
   * @summary Retrieve paginated kpis
   */
  const getPaginatedKpi = (params?: GetPaginatedKpiParams) => {
    return customInstance<GetPaginatedResponseDtoOfGetKpiDto>({
      url: `/Api/Kpi/paginate`,
      method: "GET",
      params,
    });
  };

  /**
   * Registers a new kpi record in the system based on the provided data.
   * @summary Create a new kpi
   */
  const createKpi = (kpiDto: KpiDto) => {
    return customInstance<GetKpiDto>({
      url: `/Api/Kpi/create`,
      method: "POST",
      headers: { "Content-Type": "application/json-patch+json" },
      data: kpiDto,
    });
  };

  /**
   * Modifies existing kpi details using the specified unique identifier and provided payload.
   * @summary Update existing kpi
   */
  const updateKpi = (id: number, kpiDto: KpiDto) => {
    return customInstance<GetKpiDto>({
      url: `/Api/Kpi/update/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json-patch+json" },
      data: kpiDto,
    });
  };

  /**
   * Permanently removes a kpi record from the system based on the provided identifier.
   * @summary Delete an existing kpi
   */
  const deleteKpi = (id: number) => {
    return customInstance<void>({
      url: `/Api/Kpi/delete/${id}`,
      method: "DELETE",
    });
  };

  /**
   * Retrieves information about the host machine, including OS, CPU usage, and memory status.
   * @summary Get machine information
   */
  const getMachineInfo = () => {
    return customInstance<GetMachineInfoDto>({
      url: `/Api/Machine/info`,
      method: "GET",
    });
  };

  /**
   * Fetches detailed information about a specific programtype using their identifier.
   * @summary Retrieve a programtype by ID
   */
  const getProgramTypeById = (id: number) => {
    return customInstance<GetProgramTypeDto>({
      url: `/Api/ProgramType/${id}`,
      method: "GET",
    });
  };

  /**
   * Retrieves a paginated list of all programtypes available in the system.
   * @summary Retrieve paginated programtypes
   */
  const getPaginatedProgramType = (params?: GetPaginatedProgramTypeParams) => {
    return customInstance<GetPaginatedResponseDtoOfGetProgramTypeDto>({
      url: `/Api/ProgramType/paginate`,
      method: "GET",
      params,
    });
  };

  /**
   * Registers a new programtype record in the system based on the provided data.
   * @summary Create a new programtype
   */
  const createProgramType = (programTypeDto: ProgramTypeDto) => {
    return customInstance<GetProgramTypeDto>({
      url: `/Api/ProgramType/create`,
      method: "POST",
      headers: { "Content-Type": "application/json-patch+json" },
      data: programTypeDto,
    });
  };

  /**
   * Modifies existing programtype details using the specified unique identifier and provided payload.
   * @summary Update existing programtype
   */
  const updateProgramType = (id: number, programTypeDto: ProgramTypeDto) => {
    return customInstance<GetProgramTypeDto>({
      url: `/Api/ProgramType/update/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json-patch+json" },
      data: programTypeDto,
    });
  };

  /**
   * Permanently removes a programtype record from the system based on the provided identifier.
   * @summary Delete an existing programtype
   */
  const deleteProgramType = (id: number) => {
    return customInstance<void>({
      url: `/Api/ProgramType/delete/${id}`,
      method: "DELETE",
    });
  };

  /**
   * Fetches detailed information about a specific room using their identifier.
   * @summary Retrieve a room by ID
   */
  const getRoomById = (id: number) => {
    return customInstance<GetRoomDto>({
      url: `/Api/Room/${id}`,
      method: "GET",
    });
  };

  /**
   * Retrieves a paginated list of all rooms available in the system.
   * @summary Retrieve paginated rooms
   */
  const getPaginatedRoom = (params?: GetPaginatedRoomParams) => {
    return customInstance<GetPaginatedResponseDtoOfGetRoomDto>({
      url: `/Api/Room/paginate`,
      method: "GET",
      params,
    });
  };

  /**
   * Registers a new room record in the system based on the provided data.
   * @summary Create a new room
   */
  const createRoom = (roomDto: RoomDto) => {
    return customInstance<GetRoomDto>({
      url: `/Api/Room/create`,
      method: "POST",
      headers: { "Content-Type": "application/json-patch+json" },
      data: roomDto,
    });
  };

  /**
   * Modifies existing room details using the specified unique identifier and provided payload.
   * @summary Update existing room
   */
  const updateRoom = (id: number, roomDto: RoomDto) => {
    return customInstance<GetRoomDto>({
      url: `/Api/Room/update/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json-patch+json" },
      data: roomDto,
    });
  };

  /**
   * Permanently removes a room record from the system based on the provided identifier.
   * @summary Delete an existing room
   */
  const deleteRoom = (id: number) => {
    return customInstance<void>({
      url: `/Api/Room/delete/${id}`,
      method: "DELETE",
    });
  };

  /**
   * Fetches detailed information about a specific sectordiscipline using their identifier.
   * @summary Retrieve a sectordiscipline by ID
   */
  const getSectorDisciplineById = (id: number) => {
    return customInstance<GetSectorDisciplineDto>({
      url: `/Api/SectorDiscipline/${id}`,
      method: "GET",
    });
  };

  /**
   * Retrieves a paginated list of all sectordisciplines available in the system.
   * @summary Retrieve paginated sectordisciplines
   */
  const getPaginatedSectorDiscipline = (
    params?: GetPaginatedSectorDisciplineParams,
  ) => {
    return customInstance<GetPaginatedResponseDtoOfGetSectorDisciplineDto>({
      url: `/Api/SectorDiscipline/paginate`,
      method: "GET",
      params,
    });
  };

  /**
   * Registers a new sectordiscipline record in the system based on the provided data.
   * @summary Create a new sectordiscipline
   */
  const createSectorDiscipline = (sectorDisciplineDto: SectorDisciplineDto) => {
    return customInstance<GetSectorDisciplineDto>({
      url: `/Api/SectorDiscipline/create`,
      method: "POST",
      headers: { "Content-Type": "application/json-patch+json" },
      data: sectorDisciplineDto,
    });
  };

  /**
   * Modifies existing sectordiscipline details using the specified unique identifier and provided payload.
   * @summary Update existing sectordiscipline
   */
  const updateSectorDiscipline = (
    id: number,
    sectorDisciplineDto: SectorDisciplineDto,
  ) => {
    return customInstance<GetSectorDisciplineDto>({
      url: `/Api/SectorDiscipline/update/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json-patch+json" },
      data: sectorDisciplineDto,
    });
  };

  /**
   * Permanently removes a sectordiscipline record from the system based on the provided identifier.
   * @summary Delete an existing sectordiscipline
   */
  const deleteSectorDiscipline = (id: number) => {
    return customInstance<void>({
      url: `/Api/SectorDiscipline/delete/${id}`,
      method: "DELETE",
    });
  };

  /**
   * Fetches detailed information about a specific skillsframeworktrackspecialization using their identifier.
   * @summary Retrieve a skillsframeworktrackspecialization by ID
   */
  const getSkillsFrameworkTrackSpecializationById = (id: number) => {
    return customInstance<GetSkillsFrameworkTrackSpecializationDto>({
      url: `/Api/SkillsFrameworkTrackSpecialization/${id}`,
      method: "GET",
    });
  };

  /**
   * Retrieves a paginated list of all skillsframeworktrackspecializations available in the system.
   * @summary Retrieve paginated skillsframeworktrackspecializations
   */
  const getPaginatedSkillsFrameworkTrackSpecialization = (
    params?: GetPaginatedSkillsFrameworkTrackSpecializationParams,
  ) => {
    return customInstance<GetPaginatedResponseDtoOfGetSkillsFrameworkTrackSpecializationDto>(
      {
        url: `/Api/SkillsFrameworkTrackSpecialization/paginate`,
        method: "GET",
        params,
      },
    );
  };

  /**
   * Registers a new skillsframeworktrackspecialization record in the system based on the provided data.
   * @summary Create a new skillsframeworktrackspecialization
   */
  const createSkillsFrameworkTrackSpecialization = (
    skillsFrameworkTrackSpecializationDto: SkillsFrameworkTrackSpecializationDto,
  ) => {
    return customInstance<GetSkillsFrameworkTrackSpecializationDto>({
      url: `/Api/SkillsFrameworkTrackSpecialization/create`,
      method: "POST",
      headers: { "Content-Type": "application/json-patch+json" },
      data: skillsFrameworkTrackSpecializationDto,
    });
  };

  /**
   * Modifies existing skillsframeworktrackspecialization details using the specified unique identifier and provided payload.
   * @summary Update existing skillsframeworktrackspecialization
   */
  const updateSkillsFrameworkTrackSpecialization = (
    id: number,
    skillsFrameworkTrackSpecializationDto: SkillsFrameworkTrackSpecializationDto,
  ) => {
    return customInstance<GetSkillsFrameworkTrackSpecializationDto>({
      url: `/Api/SkillsFrameworkTrackSpecialization/update/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json-patch+json" },
      data: skillsFrameworkTrackSpecializationDto,
    });
  };

  /**
   * Permanently removes a skillsframeworktrackspecialization record from the system based on the provided identifier.
   * @summary Delete an existing skillsframeworktrackspecialization
   */
  const deleteSkillsFrameworkTrackSpecialization = (id: number) => {
    return customInstance<void>({
      url: `/Api/SkillsFrameworkTrackSpecialization/delete/${id}`,
      method: "DELETE",
    });
  };

  /**
   * Fetches detailed information about a specific user using their identifier.
   * @summary Retrieve a user by ID
   */
  const getUserById = (id: string) => {
    return customInstance<GetUserDto>({
      url: `/Api/User/${id}`,
      method: "GET",
    });
  };

  /**
   * Retrieves a paginated list of all users available in the system.
   * @summary Retrieve paginated users
   */
  const getPaginatedUser = (params?: GetPaginatedUserParams) => {
    return customInstance<GetPaginatedResponseDtoOfGetUserDto>({
      url: `/Api/User/paginate`,
      method: "GET",
      params,
    });
  };

  /**
   * Registers a new user record in the system based on the provided data.
   * @summary Create a new user
   */
  const createUser = (userDto: UserDto) => {
    return customInstance<GetUserDto>({
      url: `/Api/User/create`,
      method: "POST",
      headers: { "Content-Type": "application/json-patch+json" },
      data: userDto,
    });
  };

  /**
   * Modifies existing user details using the specified unique identifier and provided payload.
   * @summary Update existing user
   */
  const updateUser = (id: string, userDto: UserDto) => {
    return customInstance<GetUserDto>({
      url: `/Api/User/update/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json-patch+json" },
      data: userDto,
    });
  };

  /**
   * Permanently removes a user record from the system based on the provided identifier.
   * @summary Delete an existing user
   */
  const deleteUser = (id: string) => {
    return customInstance<void>({
      url: `/Api/User/delete/${id}`,
      method: "DELETE",
    });
  };

  return {
    getOpenapiJson,
    getAcademicProgramById,
    getPaginatedAcademicProgram,
    createAcademicProgram,
    updateAcademicProgram,
    deleteAcademicProgram,
    getAcademicTermById,
    getPaginatedAcademicTerm,
    createAcademicTerm,
    updateAcademicTerm,
    deleteAcademicTerm,
    getAgencyById,
    getPaginatedAgency,
    createAgency,
    updateAgency,
    deleteAgency,
    login,
    googleLogin,
    microsoftLogin,
    getSession,
    registerGuest,
    logout,
    getBuildingById,
    getPaginatedBuilding,
    createBuilding,
    updateBuilding,
    deleteBuilding,
    getCampusById,
    getPaginatedCampus,
    createCampus,
    updateCampus,
    deleteCampus,
    getCollegeById,
    getPaginatedCollege,
    createCollege,
    updateCollege,
    deleteCollege,
    getCourseById,
    getPaginatedCourse,
    createCourse,
    updateCourse,
    deleteCourse,
    getCurriculumById,
    getPaginatedCurriculum,
    createCurriculum,
    updateCurriculum,
    deleteCurriculum,
    getEducationalQualityAssuranceTypeById,
    getPaginatedEducationalQualityAssuranceType,
    createEducationalQualityAssuranceType,
    updateEducationalQualityAssuranceType,
    deleteEducationalQualityAssuranceType,
    getKpiById,
    getPaginatedKpi,
    createKpi,
    updateKpi,
    deleteKpi,
    getMachineInfo,
    getProgramTypeById,
    getPaginatedProgramType,
    createProgramType,
    updateProgramType,
    deleteProgramType,
    getRoomById,
    getPaginatedRoom,
    createRoom,
    updateRoom,
    deleteRoom,
    getSectorDisciplineById,
    getPaginatedSectorDiscipline,
    createSectorDiscipline,
    updateSectorDiscipline,
    deleteSectorDiscipline,
    getSkillsFrameworkTrackSpecializationById,
    getPaginatedSkillsFrameworkTrackSpecialization,
    createSkillsFrameworkTrackSpecialization,
    updateSkillsFrameworkTrackSpecialization,
    deleteSkillsFrameworkTrackSpecialization,
    getUserById,
    getPaginatedUser,
    createUser,
    updateUser,
    deleteUser,
  };
};
export type GetOpenapiJsonResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["getOpenapiJson"]>>
>;
export type GetAcademicProgramByIdResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getEdusyncERPAPI>["getAcademicProgramById"]>
  >
>;
export type GetPaginatedAcademicProgramResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getEdusyncERPAPI>["getPaginatedAcademicProgram"]
    >
  >
>;
export type CreateAcademicProgramResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getEdusyncERPAPI>["createAcademicProgram"]>
  >
>;
export type UpdateAcademicProgramResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getEdusyncERPAPI>["updateAcademicProgram"]>
  >
>;
export type DeleteAcademicProgramResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getEdusyncERPAPI>["deleteAcademicProgram"]>
  >
>;
export type GetAcademicTermByIdResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getEdusyncERPAPI>["getAcademicTermById"]>
  >
>;
export type GetPaginatedAcademicTermResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getEdusyncERPAPI>["getPaginatedAcademicTerm"]>
  >
>;
export type CreateAcademicTermResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["createAcademicTerm"]>>
>;
export type UpdateAcademicTermResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["updateAcademicTerm"]>>
>;
export type DeleteAcademicTermResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["deleteAcademicTerm"]>>
>;
export type GetAgencyByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["getAgencyById"]>>
>;
export type GetPaginatedAgencyResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["getPaginatedAgency"]>>
>;
export type CreateAgencyResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["createAgency"]>>
>;
export type UpdateAgencyResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["updateAgency"]>>
>;
export type DeleteAgencyResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["deleteAgency"]>>
>;
export type LoginResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["login"]>>
>;
export type GoogleLoginResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["googleLogin"]>>
>;
export type MicrosoftLoginResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["microsoftLogin"]>>
>;
export type GetSessionResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["getSession"]>>
>;
export type RegisterGuestResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["registerGuest"]>>
>;
export type LogoutResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["logout"]>>
>;
export type GetBuildingByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["getBuildingById"]>>
>;
export type GetPaginatedBuildingResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getEdusyncERPAPI>["getPaginatedBuilding"]>
  >
>;
export type CreateBuildingResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["createBuilding"]>>
>;
export type UpdateBuildingResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["updateBuilding"]>>
>;
export type DeleteBuildingResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["deleteBuilding"]>>
>;
export type GetCampusByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["getCampusById"]>>
>;
export type GetPaginatedCampusResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["getPaginatedCampus"]>>
>;
export type CreateCampusResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["createCampus"]>>
>;
export type UpdateCampusResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["updateCampus"]>>
>;
export type DeleteCampusResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["deleteCampus"]>>
>;
export type GetCollegeByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["getCollegeById"]>>
>;
export type GetPaginatedCollegeResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getEdusyncERPAPI>["getPaginatedCollege"]>
  >
>;
export type CreateCollegeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["createCollege"]>>
>;
export type UpdateCollegeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["updateCollege"]>>
>;
export type DeleteCollegeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["deleteCollege"]>>
>;
export type GetCourseByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["getCourseById"]>>
>;
export type GetPaginatedCourseResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["getPaginatedCourse"]>>
>;
export type CreateCourseResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["createCourse"]>>
>;
export type UpdateCourseResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["updateCourse"]>>
>;
export type DeleteCourseResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["deleteCourse"]>>
>;
export type GetCurriculumByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["getCurriculumById"]>>
>;
export type GetPaginatedCurriculumResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getEdusyncERPAPI>["getPaginatedCurriculum"]>
  >
>;
export type CreateCurriculumResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["createCurriculum"]>>
>;
export type UpdateCurriculumResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["updateCurriculum"]>>
>;
export type DeleteCurriculumResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["deleteCurriculum"]>>
>;
export type GetEducationalQualityAssuranceTypeByIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getEdusyncERPAPI
      >["getEducationalQualityAssuranceTypeById"]
    >
  >
>;
export type GetPaginatedEducationalQualityAssuranceTypeResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getEdusyncERPAPI
      >["getPaginatedEducationalQualityAssuranceType"]
    >
  >
>;
export type CreateEducationalQualityAssuranceTypeResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getEdusyncERPAPI
      >["createEducationalQualityAssuranceType"]
    >
  >
>;
export type UpdateEducationalQualityAssuranceTypeResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getEdusyncERPAPI
      >["updateEducationalQualityAssuranceType"]
    >
  >
>;
export type DeleteEducationalQualityAssuranceTypeResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getEdusyncERPAPI
      >["deleteEducationalQualityAssuranceType"]
    >
  >
>;
export type GetKpiByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["getKpiById"]>>
>;
export type GetPaginatedKpiResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["getPaginatedKpi"]>>
>;
export type CreateKpiResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["createKpi"]>>
>;
export type UpdateKpiResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["updateKpi"]>>
>;
export type DeleteKpiResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["deleteKpi"]>>
>;
export type GetMachineInfoResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["getMachineInfo"]>>
>;
export type GetProgramTypeByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["getProgramTypeById"]>>
>;
export type GetPaginatedProgramTypeResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getEdusyncERPAPI>["getPaginatedProgramType"]>
  >
>;
export type CreateProgramTypeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["createProgramType"]>>
>;
export type UpdateProgramTypeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["updateProgramType"]>>
>;
export type DeleteProgramTypeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["deleteProgramType"]>>
>;
export type GetRoomByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["getRoomById"]>>
>;
export type GetPaginatedRoomResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["getPaginatedRoom"]>>
>;
export type CreateRoomResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["createRoom"]>>
>;
export type UpdateRoomResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["updateRoom"]>>
>;
export type DeleteRoomResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["deleteRoom"]>>
>;
export type GetSectorDisciplineByIdResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getEdusyncERPAPI>["getSectorDisciplineById"]>
  >
>;
export type GetPaginatedSectorDisciplineResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getEdusyncERPAPI>["getPaginatedSectorDiscipline"]
    >
  >
>;
export type CreateSectorDisciplineResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getEdusyncERPAPI>["createSectorDiscipline"]>
  >
>;
export type UpdateSectorDisciplineResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getEdusyncERPAPI>["updateSectorDiscipline"]>
  >
>;
export type DeleteSectorDisciplineResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getEdusyncERPAPI>["deleteSectorDiscipline"]>
  >
>;
export type GetSkillsFrameworkTrackSpecializationByIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getEdusyncERPAPI
      >["getSkillsFrameworkTrackSpecializationById"]
    >
  >
>;
export type GetPaginatedSkillsFrameworkTrackSpecializationResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getEdusyncERPAPI
      >["getPaginatedSkillsFrameworkTrackSpecialization"]
    >
  >
>;
export type CreateSkillsFrameworkTrackSpecializationResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getEdusyncERPAPI
      >["createSkillsFrameworkTrackSpecialization"]
    >
  >
>;
export type UpdateSkillsFrameworkTrackSpecializationResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getEdusyncERPAPI
      >["updateSkillsFrameworkTrackSpecialization"]
    >
  >
>;
export type DeleteSkillsFrameworkTrackSpecializationResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getEdusyncERPAPI
      >["deleteSkillsFrameworkTrackSpecialization"]
    >
  >
>;
export type GetUserByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["getUserById"]>>
>;
export type GetPaginatedUserResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["getPaginatedUser"]>>
>;
export type CreateUserResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["createUser"]>>
>;
export type UpdateUserResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["updateUser"]>>
>;
export type DeleteUserResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getEdusyncERPAPI>["deleteUser"]>>
>;
